name: NPM Publish

on:
  push:
    branches: [master]

  # These 3 lines are temporary!
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Prep .npmignore
        run: |
          cat .gitignore >> .npmignore

      # # XXX Replace with mikeal/merge-release@v4
      # - name: Dry-run publish to see which files are included
      #   run: |
      #     npm publish --access public --dry-run

      - name: publish
        uses: mikeal/merge-release@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
